version: '3.8'

services:
  webtranslatorr:
    # image: ghcr.io/zahkruin/webtranslatorr:latest
    build: .
    container_name: webtranslatorr
    ports:
      - "9811:9811"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - webtranslatorr

networks:
  webtranslatorr:
    driver: bridge
