#!/usr/bin/env python3
"""
Watcher for Readarr Torrent Blackhole directories.

Readarr saves .torrent files generated by WebTranslatorr to a blackhole
directory.  This script watches that directory, extracts the webseed URL
from each .torrent file, downloads the actual file, and saves it with the
correct extension so Readarr can import it.

Usage:
    python scripts/torrent_blackhole_watcher.py /path/to/blackhole [/path/to/output]

If *output* is omitted, files are saved to the same directory as the torrent.
"""
import os
import sys
import time
import logging
import hashlib
from pathlib import Path

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [blackhole-watcher] %(levelname)s %(message)s",
)
logger = logging.getLogger("blackhole-watcher")

# Try to use the bencode library from the project
try:
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    from bencode import bdecode
except ImportError:
    logger.error("bencode library not found. Install with: pip install bencode.py")
    sys.exit(1)

import requests

CONTENT_EXT = {
    "application/epub+zip": "epub",
    "application/x-mobipocket-ebook": "mobi",
    "application/pdf": "pdf",
}


def extract_webseed(torrent_path: str) -> str | None:
    """Extract the webseed URL from a .torrent file."""
    with open(torrent_path, "rb") as f:
        data = f.read()
    try:
        torrent = bdecode(data)
    except Exception as e:
        logger.warning("Failed to parse torrent %s: %s", torrent_path, e)
        return None

    # BEP 19: url-list
    url_list = torrent.get("url-list")
    if isinstance(url_list, list) and url_list:
        return url_list[0] if isinstance(url_list[0], str) else url_list[0].decode("utf-8", errors="replace")

    # BEP 17: httpseeds (single string)
    httpseeds = torrent.get("httpseeds")
    if httpseeds:
        return httpseeds if isinstance(httpseeds, str) else httpseeds.decode("utf-8", errors="replace")

    return None


def download_file(url: str, output_path: str) -> bool:
    """Download a file from a URL and save it."""
    try:
        logger.info("Downloading %s → %s", url, output_path)
        resp = requests.get(url, timeout=120, stream=True)
        resp.raise_for_status()

        # Determine extension from Content-Type
        content_type = resp.headers.get("Content-Type", "").split(";")[0].strip()
        ext = CONTENT_EXT.get(content_type, "bin")

        # Build output path with correct extension
        base = os.path.splitext(output_path)[0]
        final_path = f"{base}.{ext}"

        with open(final_path, "wb") as f:
            for chunk in resp.iter_content(chunk_size=65536):
                f.write(chunk)

        logger.info("Downloaded %d bytes → %s", os.path.getsize(final_path), final_path)
        return True
    except Exception as e:
        logger.error("Download failed for %s: %s", url, e)
        return False


def watch_directory(watch_dir: str, output_dir: str, poll_interval: int = 5):
    """Watch a directory for new .torrent files and process them."""
    watch_path = Path(watch_dir)
    output_path = Path(output_dir) if output_dir else watch_path
    output_path.mkdir(parents=True, exist_ok=True)

    seen: set[str] = set()
    logger.info("Watching %s → %s (interval=%ds)", watch_dir, output_dir, poll_interval)

    while True:
        try:
            for f in sorted(watch_path.glob("*.torrent")):
                fname = str(f)
                if fname in seen:
                    continue
                seen.add(fname)

                # Wait for file to be fully written
                time.sleep(1)
                if f.stat().st_size == 0:
                    seen.discard(fname)
                    continue

                webseed_url = extract_webseed(fname)
                if not webseed_url:
                    logger.warning("No webseed found in %s, skipping", fname)
                    os.remove(fname)
                    continue

                out_name = os.path.join(str(output_path), f.stem)
                if download_file(webseed_url, out_name):
                    os.remove(fname)
                    logger.info("Processed and removed: %s", fname)
                else:
                    logger.warning("Download failed, keeping torrent for retry: %s", fname)
        except KeyboardInterrupt:
            break
        except Exception as e:
            logger.error("Watch loop error: %s", e)

        time.sleep(poll_interval)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    watch_dir = sys.argv[1]
    output_dir = sys.argv[2] if len(sys.argv) > 2 else watch_dir
    watch_directory(watch_dir, output_dir)
